services:
#    jg_platform.example:
#        class: JG\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# src/OC/PlatformBundle/Resources/config/services.yml

    jg_platform.antispam:
        class: JG\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50